### ISSUE TITLE
TWRP errors

### ISSUE THREAD

**Issue by 0wnerDied** [jaegeuk/f2fs-stable#4]
after pick commit 77b2eab f2fs: rework filename handling, when entering twrp, there will be tons of errors display.

device: OnePlus 7 Pro

**Comment by jaegeuk** [comment]
Are you using casefolding + encryption?

2020년 7월 30일 (목) 오후 7:40, Neptune <notifications@github.com>님이 작성:

**Comment by 0wnerDied** [comment]
hmmm... i don't know about "casefolding" ,but it‘s true that my phone is encrypted

**Comment by jaegeuk** [comment]
Can you take a look at this merge commit with some changes for casefolding
support in Android?
https://android.googlesource.com/kernel/common/+/4f7036e47988363bf67a5cf6dbf98f0da967626f%5E1..4f7036e47988363bf67a5cf6dbf98f0da967626f/

2020년 7월 30일 (목) 오후 8:38, Neptune <notifications@github.com>님이 작성:

**Comment by 0wnerDied** [comment]
My kernel is 4.14 but not 5.4...

**Comment by jaegeuk** [comment]
Ok, 4.14 doesn't support casefolding tho.
Hmm, which android version are you using?

2020년 7월 30일 (목) 오후 9:11, Neptune <notifications@github.com>님이 작성:

**Comment by 0wnerDied** [comment]
Android 10
