### ISSUE TITLE
Clang compile bugs

### ISSUE THREAD

**Issue by asuka-mio** [jaegeuk/f2fs-stable#6]
https://github.com/jaegeuk/f2fs-stable/commit/b24f79b8e65d025b8733972c6266d442907af6ac

This commit will break clang13 in aarch64 env
gcc12 and clang13 both works well when this commit being reverted
clang13 compilation artifacts can't boot the phone with that commit but gcc12 works well

I tried fix it
https://github.com/asuka-mio/android_kernel_xiaomi_cas/commit/5bc1dc0ab638518656f70da81bde847bd14762c8
This seems fix that problem but i can't ensure all things being fixed

**Comment by asuka-mio** [comment]
https://github.com/asuka-mio/android_kernel_xiaomi_cas/commit/c977a9bab5bcafcd4f9fb1e53d6526d3d3af67d0

Sorry ,here is the new commit ,can boot with clang compile and solve deadlock

**Comment by Panchajanya1999** [comment]
> [asuka-mio/android_kernel_xiaomi_cas@c977a9b](https://github.com/asuka-mio/android_kernel_xiaomi_cas/commit/c977a9bab5bcafcd4f9fb1e53d6526d3d3af67d0)
> 
> Sorry ,here is the new commit ,can boot with clang compile and solve deadlock

gcc 12 boots for you with or without revert?

**Comment by asuka-mio** [comment]
> > [asuka-mio/android_kernel_xiaomi_cas@c977a9b](https://github.com/asuka-mio/android_kernel_xiaomi_cas/commit/c977a9bab5bcafcd4f9fb1e53d6526d3d3af67d0)
> > Sorry ,here is the new commit ,can boot with clang compile and solve deadlock
> 
> gcc 12 boots for you with or without revert?

gcc 12 boots whether with or without revert
but clang don't ,clang only boot with that commit reverted

**Comment by asuka-mio** [comment]
d5f1cc2de68339dde866a668f3814dfdcbf65d6e 
have fixed that problem, thanks!
